server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

rollbar_token: af20d6c6a0c541c5a07b3c8b20a4ab1a