spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

    datasource:
      url: ${JDBC_DATABASE_URL}

    jpa:
      show-sql: false

server:
  error:
    include-stacktrace: never

logging:
  level:
    ROOT: INFO