server:
  error:
    include-stacktrace: on_param

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html

spring:
  datasource:
    username: ""
    password: ""
    url: jdbc:h2:./taskManager

  jpa:
    show-sql: true

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG